server:
  port: 8888
datasource:
    url: localhost:3306/test
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${datasource.url}??useSLL=false&useUnicode=true&characterEncoding=utf-8
    username:
    password:
    hikari:
      maximum-pool-size: 10
      max-lifetime: 1770000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
